core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_system.urls')),
    path('', include('calendar_events.urls')),
    path('', include('menu.urls')),
    path('', include('forum.urls')),
    path('', include('pollsapp.urls')),
    path('', include('user.urls')),
    path('', include('photo_gallery.urls')),
    path('', include('adverts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo_gallery/urls.py
from django.urls import path
from django.urls import reverse_lazy
from photo_gallery.views import PhotoPostCreateView, PhotoAuthCreateView, PhotoAuthListView, PhotoUserListView, StaffPostSubmitListView, StaffPostUpdateView, PhotoPostDeleteView, PhotoPostLike

urlpatterns = [
    path('photo_posts/', PhotoAuthListView.as_view(), name='photo_posts'),
    path('photo_posts/user/', PhotoUserListView.as_view(), name='user_photos'),
    path('create_photo/', PhotoPostCreateView.as_view(), name='create_photo'),
    path('auth_request/photopost/<int:pk>', PhotoAuthCreateView.as_view(), name='auth_photo'),
    path('post_auth_list/', StaffPostSubmitListView.as_view(), name='post_auth_list'),
    path('staff_auth_form/<int:pk>', StaffPostUpdateView.as_view(), name='staff_auth_form'),
    path('delete_post/<int:pk>', PhotoPostDeleteView.as_view(), name='delete_confirm'),
    path('like/<int:pk>', PhotoPostLike.as_view(), name='post_like'),
]

app_name = 'photo_post'

photo_gallery/models.py
from django.db import models
from auth_system.models import CustomUser
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils import timezone
# Create your models here.

class PhotoPost(models.Model):
    author = models.ForeignKey(
        CustomUser,
        on_delete = models.CASCADE,
        related_name='photo_posts'
    )
    title = models.CharField(max_length=23, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to="photo-gallery/")
    likes = models.ManyToManyField(CustomUser, related_name="liked_photo_posts", blank=True)
    upload_date = models.DateTimeField()

    class Meta:
        ordering = ['-upload_date']

    def save(self, *args, **kwargs):
        if not self.pk:
            self.upload_date = timezone.now()
        self.updated_date = self.upload_date
        super(PhotoPost, self).save(*args, **kwargs)


class PhotoAuth(models.Model):
    STATUS_CHOICES = [
        ('1', 'Підтверджено'),
        ('3', 'Йде перевірка'),
        ('2', 'Відхилено')
    ]
    
    status = models.CharField(
        max_length=31,
        choices=STATUS_CHOICES,
        default="3",
    )

    photo_post = models.ForeignKey(
        PhotoPost,
        on_delete = models.CASCADE,
        related_name='auths',
        unique=True
    )

    details = models.CharField(max_length=63, null=True, blank=True)
    upload_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-status', '-upload_date']



@receiver(pre_delete, sender=PhotoPost)
def image_model_delete(sender, instance, **kwargs):
    if instance.image.name:
        instance.image.delete(False)

photo_gallery/forms.py
from django import forms
from photo_gallery.models import PhotoPost, PhotoAuth
from datetime import datetime
from django.utils import timezone


class PhotoPostForm(forms.ModelForm):
    class Meta:
        model = PhotoPost

        fields = [
            'title',
            'description',
            'image'
        ]

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.FileInput()
        }

        labels = {
            'title': 'Назва',
            'description': 'Опис',
            'image': 'Зображення:',
        }

class PhotoAuthForm(forms.ModelForm):
    class Meta:
        model = PhotoAuth

        fields = [
            'photo_post'
        ]

        widgets = {
            'photo_post': forms.Select(attrs={'class': 'form-control'})
        }

        labels = {
            'photo_post': 'Пост'
        }
    def __init__(self, *args, **kwargs):
        super(PhotoAuthForm, self).__init__(*args, **kwargs)
        self.fields['photo_post'].initial = self.initial['pk']


class PhotoAuthStaffForm(forms.ModelForm):
    class Meta:
        model = PhotoAuth

        fields = [
            'status',
            'details'
        ]

        widgets = {
            'status': forms.Select(attrs={'class': 'form-control'}),
            'details': forms.TextInput(attrs={'class': 'form-control'})
        }

        labels = {
            'status': 'Статус публікації',
            'details': 'Коментар'
        }

photo_gallery/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseBadRequest
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from photo_gallery.models import PhotoPost, PhotoAuth
from django.template.defaulttags import register
from django.core.paginator import Paginator
from photo_gallery.forms import PhotoPostForm, PhotoAuthForm, PhotoAuthStaffForm
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from photo_gallery.mixins import UserIsOwnerMixin
from django.shortcuts import redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin


root = 'photo_gallery/'
app_tag = 'photo_post:'


class PhotoPostLike(UpdateView, LoginRequiredMixin):
    model = PhotoPost

    def get_object(self):
        post_id = self.kwargs.get("pk")
        return get_object_or_404(PhotoPost, pk=post_id)

    def post(self, request, *args, **kwargs):
        post = self.get_object()
        user = request.user
        if user in post.likes.all():
            post.likes.remove(user)
        else:
            post.likes.add(user)
        post.save()
        return HttpResponseRedirect(reverse_lazy("photo_post:photo_posts"))


class PhotoPostDeleteView(DeleteView, UserIsOwnerMixin):
    model = PhotoPost
    template_name = root+"photo_post/delete_confirm.html"
    success_url = reverse_lazy("photo_post:user_photos")


@method_decorator(staff_member_required, name='dispatch')
class StaffPostSubmitListView(ListView):
    model = PhotoAuth
    template_name = root + 'staff_submit.html'
    context_object_name = 'auth_requests'
    paginate_by = 5


@method_decorator(staff_member_required, name='dispatch')
class StaffPostUpdateView(UpdateView):
    model = PhotoAuth
    template_name = root + "staff_auth_form.html"
    success_url = reverse_lazy(app_tag+"post_auth_list")
    form_class = PhotoAuthStaffForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = PhotoAuth.objects.get(id=self.object.id).photo_post
        return context


class PhotoUserListView(ListView):
    model = PhotoPost
    template_name = root + 'user_photos.html'
    context_object_name = 'photo_posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator( PhotoPost.objects.filter(author=self.request.user.id).all(), 5)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['photo_posts'] = page_obj
        return context


class PhotoAuthListView(ListView):
    model = PhotoAuth
    template_name = root + 'photo_post/list_view.html'
    context_object_name = 'photo_posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(PhotoAuth.objects.filter(status='1').all(), 5)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['photo_posts'] = page_obj
        return context


class PhotoPostCreateView(CreateView, LoginRequiredMixin):
    model = PhotoPost
    template_name = root + "photo_post/create_form.html"
    success_url = reverse_lazy(app_tag+"user_photos")
    form_class = PhotoPostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PhotoAuthCreateView(CreateView, LoginRequiredMixin, UserIsOwnerMixin):
    model = PhotoAuth
    template_name = root + "confirm_photopost.html"
    success_url = reverse_lazy(app_tag+"photo_posts")
    form_class = PhotoAuthForm
    
    def form_valid(self, form):
        form.instance.authorized = False
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        initial['pk'] = get_object_or_404(PhotoPost, id=self.kwargs['pk'])
        return initial

templates/photo_gallery/confirm_photopost.html
{% extends "index.html" %}

{% block content %}
    <a href="{%url 'photo_post:user_photos'%}" class="btn btn-primary ms-5">Назад</a>
    <form method="POST" class="w-50 m-5">
        {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Відправити запит на публікацію</button>
            
    </form>

{% endblock %}

templates/photo_gallery/staff_auth_form.html
{% extends "index.html" %}
{% load custom_tags %}
{% block content %}
    <div class="p-5">   
        <div>
            <a class="btn btn-primary" href="{%url 'photo_post:photo_posts'%}" role="button">Галерея</a>
            <a class="btn btn-primary" href="{%url 'photo_post:user_photos'%}" role="button">Мої фото</a>
            <a class="btn btn-primary" href="{%url 'photo_post:create_photo'%}" role="button">Додати фото</a>
            {% if request.user.is_staff%}
                <a class="btn btn-primary position-relative" href="{%url 'photo_post:post_auth_list'%}" role="button">
                    Заявки  публікації 
                    {%if request|to_check_photo_posts != 0%}
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            {{request|to_check_photo_posts}}
                        <span class="visually-hidden">unread messages</span>
                    {%endif%}
                </span>
                </a>
            {%endif%}
        </div>
        <div class="row mt-4">
            <div class="card col-5 ms-5 mt-3" style="width: 25rem;">
                <div class="card-text ps-2 pt-1 fw-semibold">{{post.author}}</div>
                <img src="/media/{{post.image}}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{post.title}}</h5>
                    <p class="card-text">{{post.description}}</p>
                    <a class="card-link disabled">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                        </svg>
                        {{post.likes|length}}
                    </a>
                </div>
                <div class="card-footer text-body-secondary">
                    Створено {{post.upload_date}}
                </div>
            </div>
            <form method="POST" class="w-50 m-5 col-3">
                {% csrf_token %}
                    
                    {{form.as_p}}
                    <button type="submit" class="btn btn-primary">Підтвердити</button>
                    
            </form>
        </div>
    </div>
{% endblock %}

templates/photo_gallery/staff_submit.html
{% extends "index.html" %}
{% load custom_tags %}

{% block content %}
    <div class="p-5">   
        <div>
            <a class="btn btn-primary" href="{%url 'photo_post:photo_posts'%}" role="button">Галерея</a>
            <a class="btn btn-primary" href="{%url 'photo_post:user_photos'%}" role="button">Мої фото</a>
            <a class="btn btn-primary" href="{%url 'photo_post:create_photo'%}" role="button">Додати фото</a>
            {% if request.user.is_staff%}
                <a class="btn btn-primary position-relative" href="{%url 'photo_post:post_auth_list'%}" role="button">
                    Заявки  публікації 
                    {%if request|to_check_photo_posts != 0%}
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            {{request|to_check_photo_posts}}
                        <span class="visually-hidden">unread messages</span>
                    {%endif%}
                </span>
                </a>
            {%endif%}
        </div>
        <br>
        <div>
            {% for auth_request in auth_requests %}
                <a class="card" style="width: 25rem; text-decoration: none;" href="{%url 'photo_post:staff_auth_form' auth_request.id %}">
                    <div class="card-body  border border-2 {%if auth_request.status == '3'%} border-warning bg-warning-subtle {%elif auth_request.status == '2'%} border-danger bg-danger-subtle {%elif auth_request.status == '1'%} border-success bg-success-subtle{%endif%}">
                        <p class="card-text ">
                            <h4 class="card-title{%if auth_request.status == '0'%} bg-danger {%endif%}">Фото-пост id {{auth_request.photo_post.id}}</h4>
                            Користувач: {{auth_request.photo_post.author}}
                            <br>
                            Статус перевірки: {{auth_request.get_status_display}}
                        </p>
                    </div>
                    <div class="card-footer text-body-secondary">
                        {{auth_request.upload_date}}
                    </div>
                </a>
                <br>
            {%endfor%}
            {% if paginator.page_range|length > 1 %}  
                <nav aria-label="Page navigation example">
                    <ul class="pagination ms-1 mt-3">
                        {% for page_num in paginator.page_range %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endfor %}
                    </ul>
                </nav> 
            {%endif%}
        </div>
    </div>
{% endblock %}

templates/photo_gallery/user_photos.html
{% extends "index.html" %}
{% load custom_tags %}
{% block content %}
    <div class="p-5">   
        <div>
            <a class="btn btn-primary" href="{%url 'photo_post:photo_posts'%}" role="button">Галерея</a>
            <a class="btn btn-primary" href="{%url 'photo_post:user_photos'%}" role="button">Мої фото</a>
            <a class="btn btn-primary" href="{%url 'photo_post:create_photo'%}" role="button">Додати фото</a>
            {% if request.user.is_staff%}
                <a class="btn btn-primary position-relative" href="{%url 'photo_post:post_auth_list'%}" role="button">
                    Заявки  публікації 
                    {%if request|to_check_photo_posts != 0%}
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            {{request|to_check_photo_posts}}
                        <span class="visually-hidden">unread messages</span>
                    {%endif%}
                </span>
                </a>
            {%endif%}
        </div>
        <br>
        <div class="ms-5 w-75">
            {% for post in photo_posts %}
                <!-- Button trigger modal -->
                <button type="button" class="btn " data-bs-toggle="modal" data-bs-target="#exampleModal{{post.id}}">
                    <div class="card me-3" style="width: 25rem; min-width: 250px; max-width: 400px;">
                        <div class="card-body text-start border border-2 {%if post.auths.all.0.status == '3'%} border-warning bg-warning-subtle {%elif post.auths.all.0.status == '2'%} border-danger bg-danger-subtle {%elif post.auths.all.0.status == '1'%} border-success bg-success-subtle{%endif%}">
                            <h5 class="card-title text-start">
                                {{post.title}}
                            </h5>
                            Статус: {{post.auths.all.0.get_status_display}}
                        </div>
                        <div class="card-footer text-body-secondary text-start">
                            Створено {{post.upload_date}}
                        </div>
                    </div>
                </button>
                <br>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal{{post.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h4 class="modal-title" id="exampleModalLabel{{post.id}}">
                            Перегляд
                            <br>
                            {% if post.auths.all.0.status != None%}
                                Статус публікації: '{{post.auths.all.0.get_status_display}}''
                                {%if post.auths.all.0.status == '2' and post.auths.all.0.details != None%}
                                    <br>
                                    Коментар: '{{post.auths.all.0.details}}'
                                    <br>
                                {%endif%}
                            {%else%}
                                <a href='{% url "photo_post:auth_photo" post.pk%}'>Опублікувати</a>
                            {%endif%}
                            <br>

                            <a href="{% url 'photo_post:delete_confirm' post.id%}" class="btn me-2 btn-danger">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                                </svg>
                            </a>
                        </h4>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="card" style="width: 25rem;">
                                <div class="card-text ps-2 pt-1 fw-semibold">{{post.author}}</div>
                                <img src="/media/{{post.image}}" class="card-img-top">
                                <div class="card-body">
                                    <h5 class="card-title">{{post.title}}</h5>
                                    <p class="card-text">{{post.description}}</p>
                                    <a class="card-link disabled">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                                        </svg>
                                        {{post.likes|length}}
                                    </a>
                                </div>
                                <div class="card-footer text-body-secondary">
                                    Створено {{post.upload_date}}
                                </div>
                                
                            </div>
                            
                        </div>
                        <div class="modal-footer">
                            
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                        </div>
                    </div>
                    </div>
                </div>
            {%endfor%}
            {% if photo_posts.paginator.page_range|length > 1 %}  
                <nav aria-label="Page navigation example">
                    <ul class="pagination ms-1 mt-3">
                        {% for page_num in photo_posts.paginator.page_range %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endfor %}
                    </ul>
                </nav> 
            {%endif%}
        </div>
    </div>
{% endblock %}