calendar_events/urls.py
from django.urls import path
from calendar_events.views import view_date_events, EventCreateView, EventDeleteView, EventUpdateView, EventListView
from django.urls import reverse_lazy

urlpatterns = [
    path('calendar/', view_date_events, name='calendar_events'),
    path('calendar/<int:year>/<int:month>/<int:day>', view_date_events, name='calendar_date'),
    path('event_list/', EventListView.as_view(), name='event_list'),
    path('create_event/', EventCreateView.as_view(), name="create_event"),
    path('delete_event/<int:pk>', EventDeleteView.as_view(), name="delete_event"),
    path('update_event/<int:pk>', EventUpdateView.as_view(), name="update_event"),
]

app_name = 'calendar_event'

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_system.urls')),
    path('', include('calendar_events.urls')),
    path('', include('menu.urls')),
    path('', include('forum.urls')),
    path('', include('pollsapp.urls')),
    path('', include('user.urls')),
    path('', include('photo_gallery.urls')),
    path('', include('adverts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calendar_events/models.py
from django.db import models
from auth_system.models import CustomUser
from django.utils import timezone

class Event(models.Model):
    creator = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="events"
    )

    name = models.CharField(max_length=63)
    description = models.TextField(blank=True, null=True)

    scheduled_date = models.DateField(default=timezone.now)
    scheduled_time = models.TimeField(null=True)
    date_created = models.DateTimeField(auto_now=True)

    meeting_url = models.URLField(blank=True, null=True)

    class Meta:
        ordering = ["scheduled_date"]

    
    def time(self):
        return self.scheduled_time.strftime("%H:%M")

calendar_events/forms.py
from django import forms
from calendar_events.models import Event
from datetime import datetime
from django.utils import timezone


class EventCreateForm(forms.ModelForm):
    class Meta:
        model = Event

        fields = [
            'name',
            'description',
            'scheduled_date',
            'scheduled_time',
            'meeting_url',
        ]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'scheduled_date': forms.SelectDateWidget(
                years=range(
                    timezone.now().year,
                    timezone.now().year + 5
                )
            ),
            'scheduled_time': forms.TimeInput(),
            'meeting_url': forms.TextInput(attrs={'class': 'form-control'})
        }

        labels = {
            'name': 'Назва події',
            'description': 'Опис',
            'scheduled_date': 'Дата події',
            'scheduled_time': 'Час події (Окрім 00:00)',
            'meeting_url': 'Посилання на онлайн-зустріч',
        }


    def __init__(self, *args, **kwargs):
        super(EventCreateForm, self).__init__(*args, **kwargs)
        self.fields['scheduled_date'].initial = timezone.now().date()
        self.fields['scheduled_time'].initial = timezone.now().date()

calendar_events/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseBadRequest
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from calendar_events.models import Event
from django.utils import timezone
from django.template.defaulttags import register
from calendar_events.events_func import next_date, previous_date, selected_date_events, month_events
from calendar_events.forms import EventCreateForm
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from calendar_events.mixins import UserIsOwnerMixin
import calendar
import datetime


root = "calendar_events/"
months = [
    ("Січень", "січня"),
    ("Лютий", "лютого"),
    ("Березень", "березня"),
    ("Квітень", "квітня"),
    ("Травень", "травня"),
    ("Червень", "червня"),
    ("Липень", "липня"),
    ("Серпень", "серпня"),
    ("Вересень", "вересня"),
    ("Жовтень", "жовтня"),
    ("Листопад", "листопада"),
    ("Грудень", "грудня")
]


def view_date_events(request, day=None, month=None, year=None):
    if not day or not month or not year:
        date = timezone.now()
    else:
        try:
            date = datetime.datetime(year, month, day)
        except:
            return HttpResponseBadRequest("Date not found") 
    
    paginator = Paginator(selected_date_events(date), 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        "calendar": calendar.Calendar().monthdays2calendar(date.year, date.month),
        "today": timezone.now(),
        "date": date,
        "selected_date_events": page_obj,
        "events_month": month_events(date),
        "month_name": months[date.month-1],
        "next": next_date(date),
        "previous": previous_date(date),
    }

    return render(
        template_name=root+"calendar_page.html",
        context=context,
        request=request
    )

class EventListView(ListView, LoginRequiredMixin):
    model = Event
    template_name = root + "event/event_list.html"
    context_object_name = 'events'
    paginate_by = 7


class EventCreateView(CreateView, LoginRequiredMixin):
    model = Event
    template_name = root + "event/create_form.html"
    form_class = EventCreateForm
    success_url = reverse_lazy("calendar_event:calendar_events")

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class EventDeleteView(DeleteView, LoginRequiredMixin, UserIsOwnerMixin):
    model = Event
    template_name = root+"event/delete_confirm.html"
    success_url = reverse_lazy("calendar_event:calendar_events")


class EventUpdateView(UpdateView, LoginRequiredMixin, UserIsOwnerMixin):
    model = Event
    template_name = root + "event/update_event.html"
    success_url = reverse_lazy("calendar_event:calendar_events")
    form_class = EventCreateForm

templates/calendar_events/calendar_page.html
{% extends 'index.html' %}
{% load custom_tags %}


{% block content %}
    <style>
        .calendar-container {
            max-width: 1000px;
            max-height: 500px;
            min-width: 400px;
            margin: auto;
        }
    </style>
    <p class="d-inline-flex gap-1 ml-5">
        <a href="{%url 'calendar_event:calendar_events'%}" class="btn btn-primary mr-1">Календар</a>
        <a href="{%url 'calendar_event:event_list'%}" class="btn btn-primary mr-1">Список подій</a>
        <a href="{%url 'calendar_event:create_event'%}" class="btn btn-primary mr-1">Створити подію</a>
    </p>
    <br>
    <br>
    <div class="container-fluid text-center">
        <div class="row calendar-container ml-3">
            <div class="col-md-8 mb-3 border rounded pb-2 bg-white ">
                <div class="row text-center p-3 bg-primary rounded-3 text-white">
                    <div class="col">
                        <a href="{% url 'calendar_event:calendar_date' year=previous.year month=previous.month day=previous.day%}" class="text-white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
                            </svg>
                        </a>
                    </div>
                    <div class="col h4">{{month_name.0}} {{date.year}}</div>
                    <div class="col">
                        <a href="{% url 'calendar_event:calendar_date' year=next.year month=next.month day=next.day%}" class="text-white bold">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
                            </svg>
                        </a>
                    </div>
                </div>
                <div class="row d-flex justify-content-between p-2 fw-lighter"> 
                    <div class="col">Пн</div>
                    <div class="col">Вт</div>
                    <div class="col">Ср</div>
                    <div class="col">Чт</div>
                    <div class="col">Пт</div>
                    <div class="col">Сб</div>
                    <div class="col">Нд</div>
                </div>
                {% for week in calendar %}
                    {% if calendar.0 == week %}
                        <div class="row d-flex justify-content-between g-1 mt-1" style="height:30px">
                    {% else %}
                        <div class="row d-flex justify-content-between border-top g-1 mt-1" style="height:30px">
                    {%endif%}
                        {% for day in week %}
                            <div class="col mb-2 p-1">
                                {% if day.0 == 0 %}
                                    <div aria-label="Empty">
                                        {{' '}}
                                    </div>
                                {% elif day.0 == date.day %}
                                    <a class="btn btn-primary btn-square-md" style="border-style: none;" aria-disabled="true">
                                        {{day.0}}
                                    </a>
                                {% elif day.0 == today.day and date.month == today.month and date.year == today.year %}
                                    <a href="{% url 'calendar_event:calendar_date' year=date.year month=date.month day=day.0%}" type="button" class="btn text-center text-black border border-warning rounded-3" style=" border-style: none;">
                                        {{day.0}}
                                    </a>
                                {%else%}
                                    {% if day.0 in events_month %}
                                        <a href="{% url 'calendar_event:calendar_date' year=date.year month=date.month day=day.0%}" type="button" class="btn text-center text-black  border border-primary rounded-3 " style=" border-style: none;">
                                            {{day.0}}
                                        </a>
                                    {% else %}
                                        <a href="{% url 'calendar_event:calendar_date' year=date.year month=date.month day=day.0%}" type="button" class="btn text-center text-black" style=" border-style: none;">
                                            {{day.0}}
                                        </a>
                                    {%endif%}
                                {%endif%}
                            </div>
                        {% endfor %}
                    </div>
                    <br>
                {% endfor %}
            </div>
            
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header fs-3 text-white" style="background-color: #FE5E54;">
                        Події на {% if date.day == today.day and date.month == today.month and date.year == today.year %} сьогодні {%else%}{{date.day}} {{month_name.1}}{%endif%}
                    </div>
                    <div class="card-body">
                        {% if selected_date_events %}
                            {% for event in selected_date_events %}
                                <div class="card text-left mb-1">
                                    <div class="card-header">
                                        {{event.name}}
                                        {{event.scheduled}}
                                        {% if event.time != '00:00'%}
                                            {{event.time}}
                                        {%endif%}
                                        
                                    </div>
                                    <div class="card-body">
                                        {%if event.description %}
                                            {% if event.description|length > 13 %}
                                                <button type="button" class="btn btn-outline-primary mb-2" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                                                    Опис
                                                </button>
                                                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                                    <div class="modal-dialog">
                                                      <div class="modal-content">
                                                        <div class="modal-header">
                                                          <h1 class="modal-title h5" id="staticBackdropLabel">Опис</h1>
                                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            {{event.description}}
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрити</button>
                                                        </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                            {%else%}
                                                Опис: {{event.description}}
                                            {%endif%}
                                            <br>
                                        {%endif%}

                                        {% if event.meeting_url%}
                                            <a href="{{event.meeting_url}}" target=”_blank”>
                                                Посилання
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-link-45deg" viewBox="0 0 16 16">
                                                    <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1 1 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4 4 0 0 1-.128-1.287z"/>
                                                    <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243z"/>
                                                  </svg>
                                            </a>
                                            <br>
                                        {%endif%}
                                        {% if event.time != '00:00' %}
                                            Час події: {{event.time}}
                                        {%endif%}
                                    </div>
                                    <div class="card-text m-1">
                                        <a href="{% url 'calendar_event:update_event' event.id%}" style="text-decoration: none;">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                                            </svg>
                                        </a>
                                        <a href="{% url 'calendar_event:delete_event' event.id%}" style="text-decoration: none;">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                            </svg>
                                        </a>
                                    </div>
                                </div>
                            {%endfor%}
                            {% if selected_date_events.paginator.page_range|length > 1%}
                                
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination ml-1 mt-3">
                                        {% for page_num in selected_date_events.paginator.page_range %}
                                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </nav> 
                            {%endif%}
                        {% else %}
                            Подій не знайдено
                        {% endif %}
                            
                    </div>
                </div>
            </div>
            
        </div>
    </div>
{% endblock %}