core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_system.urls')),
    path('', include('calendar_events.urls')),
    path('', include('menu.urls')),
    path('', include('forum.urls')),
    path('', include('pollsapp.urls')),
    path('', include('user.urls')),
    path('', include('photo_gallery.urls')),
    path('', include('adverts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('user-list', UsersList.as_view(), name='user-list'),
    path('profile/<int:pk>/', UserProfile.as_view(), name='profile'),
    path('create-portfolio', CreatePortfolio.as_view(), name='create-portfolio'),
    path('delete-portfolio', DeletePortfolio.as_view(), name='delete-portfolio'),
    path('create-project', CreateProject.as_view(), name='create-project'),
    path('delete-project/<int:pk>/', DeleteProject.as_view(), name='delete-project'),
]

app_name = 'user'

user/models.py
from django.db import models
from auth_system.models import CustomUser


class Project(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='project')

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    git_url = models.URLField(blank=True)


class Image(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='project_imgs/', default='avatars/default/default.png', blank=True, null=True)


class Portfolio(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    projects = models.ManyToManyField(Project, blank=True, related_name='portfolio')

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    occupation = models.CharField(max_length=100)
    bio = models.CharField(max_length=250)
    github_url = models.URLField(blank=True)
    tg = models.URLField(blank=True)
    email = models.EmailField(blank=True)
    adress = models.CharField(max_length=250, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)

user/forms.py
from .models import Portfolio
from django import forms

class PortfolioCreationForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = ('first_name',
                'last_name',
                'occupation',
                'bio',
                'github_url',
                'tg',
                'email',
                'adress',
                'phone',)

user/views.py
from django.shortcuts import render
from auth_system.models import CustomUser
from django.views.generic import DetailView, CreateView, View, ListView
from .models import *
from .forms import PortfolioCreationForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.core.paginator import Paginator


class UserProfile(DetailView):
    model = CustomUser
    template_name = 'user/user_profile.html'
    context_object_name = 'userp'

    def get(self, request, *args, **kwargs):
        user_is_owner = self.get_object().id == request.user.id
        portfolio = Portfolio.objects.filter(user=self.get_object())
        user = CustomUser.objects.get(id=self.get_object().id)
        projects = Project.objects.filter(user=self.get_object())
        for project in projects:
            if project.images.count() > 1:
                for img in project.images.all():
                    print(img.image)
            else:
                if project.images.exists:
                    print(project.images.first)
        if portfolio:
            project_count = projects.count()
            return render(request, self.template_name, {'portfolio': portfolio[0], 'project_count': project_count if project_count else 0, 'user': user, 'user_is_owner': user_is_owner, 'projects':projects})
        else:
            return render(request, self.template_name, {'portfolio': None, 'user': user, 'user_is_owner': user_is_owner, 'project_count':0})


class UsersList(View):
    def get(self, request, *args, **kwargs):
        users = CustomUser.objects.all()
        paginator = Paginator(users, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'user/users_list.html', {'page_obj':page_obj})


class CreatePortfolio(CreateView):
    model = Portfolio
    template_name = 'user/create_portfolio.html'
    form_class = PortfolioCreationForm
    success_url = reverse_lazy('menu:index')

    def post(self, request, *args, **kwargs):
        form = PortfolioCreationForm(request.POST)
        Portfolio.objects.create(
            first_name=form.data['first_name'],
            last_name=form.data['last_name'],
            occupation = form.data['occupation'],
            bio = form.data['bio'],
            github_url=form.data['github_url'],
            tg=form.data['tg'],
            email=form.data['email'],
            adress=form.data['adress'],
            phone=form.data['phone'],
            user=CustomUser.objects.get(id=request.user.id)
        ).save()
        return HttpResponseRedirect(self.success_url)


class DeletePortfolio(View):
    def get(self, request, *args, **kwargs):
        portfolio = Portfolio.objects.get(user=request.user)
        portfolio.delete()
        return HttpResponseRedirect(reverse_lazy('menu:index'))


class CreateProject(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'user/create_project.html')

    def post(self, request, *args, **kwargs):
        portfolio = Portfolio.objects.get(user=request.user)
        project = Project.objects.create(
            title=request.POST['title'],
            git_url=request.POST['git_url'],
            description=request.POST['description'],
            user = request.user
        ).save()
        image1 = request.FILES.get('image1')
        image2 = request.FILES.get('image2')
        image3 = request.FILES.get('image3')
        if image1:
            Image.objects.create(project=project, image=image1)
        if image2:
            Image.objects.create(project=project, image=image2)
        if image3:
            Image.objects.create(project=project, image=image3)

        portfolio.projects.add(project)
        return HttpResponseRedirect(reverse_lazy('menu:index'))


class DeleteProject(View):
    def get(self, request, *args, **kwargs):
        project = Project.objects.get(id=kwargs['pk'])
        project.delete()
        return HttpResponseRedirect(reverse_lazy('menu:index'))

templates/user/create_portfolio.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit"> Давай</button>
    </form>
</div>
{% endblock %}

templates/user/create_project.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
    <h1>Create Project</h1>
    <form method="post" id="project-form" enctype='multipart/form-data'>
    {% csrf_token %}
    <div class="form-group">
        <label for="title">Project Name:</label>
        <input type="text" class="form-control" id="title" name="title" required>
    </div>

    <div class="form-group">
        <label for="description">Description:</label>
        <textarea class="form-control" id="description" name="description" rows="1" required></textarea>
    </div>

    <div class="form-group">
        <label for="git_url">Github url:</label>
        <textarea class="form-control" id="git_url" name="git_url" rows="1" required></textarea>
    </div>

    
    <div class="image-container">
        <div class="form-group">
            <label for="image1">Project Image 1:</label>
            <div id="file-inputs">
                <input type="file" class="form-control-file" id="image1" name="image1" required>
            </div>
        </div>
    </div>

    <div class="image-container">
        <div class="form-group">
            <label for="image2">Project Image 2:</label>
            <div id="file-inputs">
                <input type="file" class="form-control-file" id="image2" name="image2" required>
            </div>
        </div>
    </div>

    <div class="image-container">
        <div class="form-group">
            <label for="image3">Project Image 3:</label>
            <div id="file-inputs">
                <input type="file" class="form-control-file" id="image3" name="image3" required>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Create Project</button>
    </form>
</div>

<script>
const fileInput = document.getElementById('image');
const fileInputsContainer = document.getElementById('file-inputs');

fileInput.addEventListener('change', function() {
  // Check if a file is selected
    if (this.files.length > 0) {
    // Clone the existing input element
    const newInput = this.cloneNode(true);
    // Clear the value of the cloned input
    newInput.value = '';
    // Add the new input to the container
    fileInputsContainer.appendChild(newInput);
    }
});
</script>
</body>
</html>
{% endblock %}

templates/user/portfolio.html
<style>
  @media (max-width: 768px) {
  .carousel-image {
    width: 75%;
  }
}

@media (min-width: 768px) and (max-width: 992px) {
  .carousel-image {
    width: 60%;
  }
}
</style>

  <section style="background-color: #eee;">
    {% if user_is_owner %}
    <div class="container" style="padding: 3px;">
      <a href="{% url 'user:delete-portfolio' %}" class="btn btn-primary">Delete Portfolio</a>
      <a href="{% url 'user:create-project' %}" class="btn btn-primary">Add project</a>
    </div>
    {% endif %}
    <div class="container py-5">
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
              <img src="{{user.avatar.url}}" alt="avatar"
                class="rounded-circle img-fluid" style="width: 150px;">
              <h5 class="my-3">{{user.username}}</h5>
              <p class="text-muted mb-1">{{portfolio.occupation}}</p>
              <p class="text-muted mb-4">{{portfolio.bio}}</p>
              <div class="d-flex justify-content-center mb-2">
                <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-primary ms-1">Message</button>
              </div>
            </div>
          </div>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body p-0">
              <ul class="list-group list-group-flush rounded-3">
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fa-brands fa-telegram"></i>
                  <p class="mb-0">{{portfolio.tg}}</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-github fa-lg text-body"></i>
                  <p class="mb-0">{{portfolio.github_url}}</p>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Full Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{portfolio.first_name}} {{portfolio.last_name}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{portfolio.email}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{portfolio.phone}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Address</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{portfolio.adress}}</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            {% for project in projects %}
            <div class="card" style="border-radius: 15px;" >
              <div class="card-body p-4">
                <h3 class="mb-3">{{project.title}}</h3>
                <p class="small mb-0">{{project.description}}</p>
                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-inner">
                    {% if project.images.count > 1 %}
                      {% for img in project.images.all %}
                        <div class="carousel-item active">
                          <img src="{{ img.image.url }}" class="d-block w-100 carousel-image" alt="Image {{ forloop.counter }}" style="width: 300px; height: 300px;">
                        </div>
                      {% endfor %}
                    {% else %}
                      {% if project.images.exists %}
                        <div class="carousel-item active">
                          <img src="{{ project.images.first.image.url }}" class="d-block w-100 carousel-image" alt="Single Image" style="width: 300px; height: 300px;">
                        </div>  
                      {% endif %}
                    {% endif %}
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Предыдущий</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Следующий</span>
                  </button>
                </div>
                <hr class="my-4">
                <div class="d-flex justify-content-start align-items-center">
                  <a href="{{project.git_url}}"><p class="mb-0 text-uppercase"><i class="fas fa-link ms-4 me-2"></i> <span
                      class="text-muted small">github link</span></p></a>
                    <span class="ms-3 me-4">|</span></p>
                  <a href="#!">
                    <img src="{{user.avatar.url}}" alt="avatar"
                      class="img-fluid rounded-circle me-1" width="35">
                  </a>
                  {% if user_is_owner %}
                  <a href="{% url 'user:delete-project' project.id %}"><i class="fa-sharp fa-solid fa-trash"></i></a>
                  {% endif %}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>

templates/user/user_profile.html
{% extends 'index.html' %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" /> 


<section class="w-100 px-4 py-5" style="background-color: rgba(105,92,254,255); border-radius: .5rem .5rem 0 0;">
    <div class="row d-flex justify-content-center">
        <div class="col col-md-9 col-lg-7 col-xl-6">
        <div class="card" style="border-radius: 15px;">
            <div class="card-body p-4">
            <div class="d-flex">
                <div class="flex-shrink-0">
                <img src="{{user.avatar.url}}"
                    alt="Generic placeholder image" class="img-fluid" style="width: 180px; border-radius: 10px;">
            </div>
            <div class="flex-grow-1 ms-3">
                <h5 class="mb-1">{{user.username}}</h5>
                <p class="mb-2 pb-1">{{user.description}}</p>
                <div class="d-flex justify-content-start rounded-3 p-2 mb-2 bg-body-tertiary">
                    <div>
                        <p class="small text-muted mb-1">Projects </p>
                        <p class="mb-0">{{project_count}}</p>
                    </div>
                    <div class="px-3">
                        <p class="small text-muted mb-1">Rating</p>
                        <p class="mb-0">{{user.raiting}} <i class="fa-solid fa-star"></i></p>
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
    </div>
    </div>
</section>
{% if portfolio %}
{% include 'user/portfolio.html' %}
{% else %}
    {% if user_is_owner %}
<div class="container">
    <a href="{% url 'user:create-portfolio' %}" class="btn btn-primary">Create Portfolio</a>
</div>
    {% else %}
    {% endif %}
{% endif %}

{% endblock %}

templates/user/users_list.html
{% extends 'index.html' %}

{% block content %}
<style>
    body{
padding-top:40px;
background:#E6E6FA    
}
.card {
    box-shadow: 0 20px 27px 0 rgb(0 0 0 / 5%);
}

.avatar-md {
    height: 5rem;
    width: 5rem;
}

.fs-19 {
    font-size: 19px;
}

.primary-link {
    color: #314047;
    -webkit-transition: all .5s ease;
    transition: all .5s ease;
}

a {
    color: #02af74;
    text-decoration: none;
}

.bookmark-post .favorite-icon a, .job-box.bookmark-post .favorite-icon a {
    background-color: #da3746;
    color: #fff;
    border-color: danger;
}
.favorite-icon a {
    display: inline-block;
    width: 30px;
    height: 30px;
    font-size: 18px;
    line-height: 30px;
    text-align: center;
    border: 1px solid #eff0f2;
    border-radius: 6px;
    color: rgba(173,181,189,.55);
    -webkit-transition: all .5s ease;
    transition: all .5s ease;
}


.candidate-list-box .favorite-icon {
    position: absolute;
    right: 22px;
    top: 22px;
}
.fs-14 {
    font-size: 14px;
}
.bg-soft-secondary {
    background-color: rgba(116,120,141,.15)!important;
    color: #74788d!important;
}

.mt-1 {
    margin-top: 0.25rem!important;
}
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="candidate-list">
                    {% for user in page_obj %}
                    <div class="candidate-list-box card mt-4">
                        <div class="p-4 card-body">
                            <div class="align-items-center row">
                                <div class="col-auto">
                                    <div class="candidate-list-images">
                                        <a href="#"><img src="{{user.avatar.url}}" alt="" class="avatar-md img-thumbnail rounded-circle" /></a>
                                    </div>
                                </div>
                                <div class="col-lg-5">
                                    <div class="candidate-list-content mt-3 mt-lg-0">
                                        <h5 class="fs-19 mb-0">
                                            <a class="primary-link" href="{% url 'user:profile' user.id %}">{{user.username}}</a><span class="badge bg-success ms-1"><i class="mdi mdi-star align-middle"></i>{{user.raiting}}</span>
                                        </h5>
                                        <p class="text-muted mb-2">{{user.description}}</p>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="mt-2 mt-lg-0 d-flex flex-wrap align-items-start gap-1">
                                        <span class="badge bg-soft-secondary fs-14 mt-1">{{user.access}}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="favorite-icon">
                                <a href="#"><i class="mdi mdi-heart fs-18"></i></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="mt-4 pt-2 col-lg-12">
                <nav aria-label="Page navigation example">
                    <div class="pagination job-pagination mb-0 justify-content-center">
                        {% for page_num in page_obj.paginator.page_range %}
                            {% if page_obj.number != page_num %}
                                <li class="page-item active"><a class="page-link" href="?page={{page_num}}">{{ page_num }}</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{page_num}}">{{ page_num }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </div>
                </nav>
            </div>
        </div>
    </div>
</section>
{% endblock %}