core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_system.urls')),
    path('', include('calendar_events.urls')),
    path('', include('menu.urls')),
    path('', include('forum.urls')),
    path('', include('pollsapp.urls')),
    path('', include('user.urls')),
    path('', include('photo_gallery.urls')),
    path('', include('adverts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import ListCategoriesView, CategoriesTopicsView, TopicsPostsView, PostDetailView, CategoryCreateView, TopicCreateView, CategoryUpdateView, TopicUpdateView, PostUpdateView, CategoryDeleteView, TopicDeleteView, PostDeleteView

#comment for test

urlpatterns = [
    path('categories/', login_required(ListCategoriesView.as_view()), name='all-categories'),
    path('category/<int:category_id>/topics', login_required(CategoriesTopicsView.as_view()), name='topics'),
    path('topic/<int:topic_id>/posts', login_required(TopicsPostsView.as_view()), name='posts'),
    path('post/<int:pk>/', login_required(PostDetailView.as_view()), name='post-detail'),
    path('category/create/', login_required(CategoryCreateView.as_view()), name='create-category'),
    path('category/<int:category_id>/topic/create/', login_required(TopicCreateView.as_view()), name='create-topic'),
    path('category/<int:pk>/update/', login_required(CategoryUpdateView.as_view()), name='update-category'),
    path('topic/<int:pk>/update/', login_required(TopicUpdateView.as_view()), name='update-topic'),
    path('post/<int:pk>/update/', login_required(PostUpdateView.as_view()), name='update-post'),
    path('category/<int:pk>/delete/', login_required(CategoryDeleteView.as_view()), name='delete-category'),
    path('topic/<int:pk>/delete/', login_required(TopicDeleteView.as_view()), name='delete-topic'),
    path('post/<int:pk>/delete/', login_required(PostDeleteView.as_view()), name='delete-post')
]

app_name = 'forum'

forum/models.py
from django.db import models
from auth_system.models import CustomUser

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=98)

    def __str__(self) -> str:
        return f"Category - {self.name}"
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Topic(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='topics')
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='topics')

    title = models.CharField(max_length=98)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"Topic {self.title} from {self.category.name} category"
    
    class Meta:
        verbose_name = 'Topic'
        verbose_name_plural = 'Topics'


class Post(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='posts')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='posts')

    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"post by {self.author.username} to {self.topic.title}"
    
    class Meta:
        ordering = ['created_at']
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

forum/forms.py
from django import forms
from .models import Category, Topic, Post

class CategoryCreationForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'name'
        ]

        labels = {
            'name': 'Enter category name:'
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }


class TopicCreationForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = [
            'title'
        ]

        labels = {
            'title': 'Enter topic title:'
        }

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'})
        }


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'content'
        ]

        labels = {
            'content': ''
        }

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control'})
        }


class CategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'name'
        ]

        labels = {
            'name': 'Enter new category name:'
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }


class TopicUpdateForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = [
            'title'
        ]

        labels = {
            'title': 'Enter new topic title:'
        }

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'})
        }


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'content'
        ]

        labels = {
            'content': 'New text'
        }

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control'})
        }

forum/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, View, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from .models import Category, Topic, Post
from .forms import CategoryCreationForm, TopicCreationForm, PostCreationForm, CategoryUpdateForm, TopicUpdateForm, PostUpdateForm
from .mixins import CreatorIsOwnerMixin, AuthorIsOwnerMixin

# Create your views here.

class ListCategoriesView(ListView):
    model = Category
    template_name = 'forum/categories.html'
    context_object_name = 'categories'


class CategoriesTopicsView(View):
    template_name = 'forum/topics.html'
    
    def get_queryset(self, **kwargs):
        category = get_object_or_404(Category, id=kwargs.get('category_id'))
        queryset = category.topics.all()

        return queryset
    
    def get(self, request, *args, **kwargs):
        category = get_object_or_404(Category, id=kwargs.get('category_id'))
        topics = self.get_queryset(**kwargs)

        paginator = Paginator(topics, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'category': category,
            'topics': topics,
            'page_obj': page_obj
        }

        return render(
            request,
            self.template_name,
            context
        )
    

class TopicsPostsView(View):
    template_name = 'forum/posts.html'
    form_class = PostCreationForm
    
    def get_queryset(self, **kwargs):
        topic = get_object_or_404(Topic, id=kwargs.get('topic_id'))
        queryset = topic.posts.all()

        return queryset
    
    def get(self, request, *args, **kwargs):
        topic = get_object_or_404(Topic, id=kwargs.get('topic_id'))
        posts = self.get_queryset(**kwargs)
        form = self.form_class

        paginator = Paginator(posts, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'topic': topic,
            'posts': posts,
            'form': form,
            'page_obj': page_obj
        }

        return render(
            request,
            self.template_name,
            context
        )
    
    def post(self, request, *args, **kwargs):
        topic = Topic.objects.get(id=kwargs.get('topic_id'))
        form = self.form_class(request.POST)

        context = {
            'topic': topic,
            'form': form
        }

        if form.is_valid():
            form.instance.author_id = self.request.user.id
            topic_id = kwargs.get('topic_id')
            topic = Topic.objects.get(id=topic_id)
            post = form.save(commit=False)
            post.topic = topic
            post.save()
            topic.posts.add(post)
            return redirect('forum:posts', topic_id=topic_id)
        
        return render(
            request,
            self.template_name,
            context
        )
    

class PostDetailView(DetailView):
    model = Post
    template_name = 'forum/post-detail.html'
    context_object_name = 'post'


def is_user_moderator_or_admin(user):
    return user.is_authenticated and (user.access == 'moder' or user.is_staff)


@method_decorator(user_passes_test(is_user_moderator_or_admin), name='dispatch')
class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryCreationForm
    template_name = 'forum/category-creation.html'
    success_url = reverse_lazy('forum:all-categories')


class TopicCreateView(View):
    template_name = 'forum/topic-creation.html'
    form_class = TopicCreationForm

    def get(self, request, *args, **kwargs):
        category = Category.objects.get(id=kwargs.get('category_id'))
        form = self.form_class

        context = {
            'category': category,
            'form': form
        }

        return render(
            request,
            self.template_name,
            context
        )

    def post(self, request, *args, **kwargs):
        category = Category.objects.get(id=kwargs.get('category_id'))
        form = self.form_class(request.POST)

        context = {
            'category': category,
            'form': form
        }

        if form.is_valid():
            form.instance.creator_id = self.request.user.id
            category_id = kwargs.get('category_id')
            category = Category.objects.get(id=category_id)
            topic = form.save(commit=False)
            topic.category = category
            topic.save()
            category.topics.add(topic)
            return redirect('forum:topics', category_id=category_id)
        
        return render(
            request,
            self.template_name,
            context
        )
    
@method_decorator(user_passes_test(is_user_moderator_or_admin), name='dispatch')
class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryUpdateForm
    template_name = 'forum/category-update.html'
    success_url = reverse_lazy('forum:all-categories')


class TopicUpdateView(CreatorIsOwnerMixin, UpdateView):
    model = Topic
    form_class = TopicUpdateForm
    template_name = 'forum/topic-update.html'
    
    def get_success_url(self) -> str:
        category_id = self.object.category_id
        return reverse_lazy('forum:topics', kwargs={'category_id': category_id})
    

class PostUpdateView(AuthorIsOwnerMixin, UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name = 'forum/post-update.html'

    def dispatch(self, request, *args, **kwargs):
        instance = self.get_object()
        if instance.author != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)
    
    def get_success_url(self) -> str:
        topic_id = self.object.topic_id
        return reverse_lazy('forum:posts', kwargs={'topic_id': topic_id})
    

@method_decorator(user_passes_test(is_user_moderator_or_admin), name='dispatch')
class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy('forum:all-categories')


class TopicDeleteView(CreatorIsOwnerMixin, DeleteView):
    model = Topic

    def get_success_url(self) -> str:
        category_id = self.object.category_id
        return reverse_lazy('forum:topics', kwargs={'category_id': category_id})
    

class PostDeleteView(AuthorIsOwnerMixin, DeleteView):
    model = Post

    def get_success_url(self) -> str:
        topic_id = self.object.topic_id
        return reverse_lazy('forum:posts', kwargs={'topic_id': topic_id})

templates/forum/categories.html
{% extends 'index.html' %}
{% block content %}
    <div class="container">
        <h2 class="mb-4">Categories</h2>
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <ul class="list-group">
                            {% if categories %}
                                {% for category in categories %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <a href="{% url 'forum:topics' category.id %}" class="text-dark link-offset-2 link-underline link-underline-opacity-0"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                                            <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105"/>
                                        </svg> {{ category.name }}</a>
                                        {% if request.user.access == "moder" or request.user.access == "admin" %}
                                            <div class="btn-group">
                                                <a href="{% url 'forum:update-category' category.id %}" class="btn btn-outline-secondary btn-sm">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                                                        <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001"/>
                                                    </svg>
                                                </a>
                                                <a href="{% url 'forum:delete-category' category.id %}" class="btn btn-outline-danger btn-sm">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                                                    </svg>
                                                </a>
                                            </div>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            
                            {% else %}
                            No categories
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                {% if request.user.access == "moder" or request.user.access == "admin" %}
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">Actions (moder, admin only)</h5>
                            <a href="{% url 'forum:create-category' %}" class="btn btn-primary btn-block">Create Category</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/forum/category-creation.html
{% extends 'index.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Category Creation</h2>
                        <form method="post" action="{% url 'forum:create-category' %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/forum/category-update.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Category update</h2>
                    <form method="post" action="{% url 'forum:update-category' category.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>                
{% endblock content %}

templates/forum/category_confirm_delete.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Are you sure you want to delete {{ category.name }} category?</h2>
                    <form method="post" action="{% url 'forum:delete-category' category.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class='btn btn-danger' type="submit">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>                
{% endblock content %}

templates/forum/post-detail.html
{% extends 'base.html' %}
{% block content %}
    <h2>{{ post.title }}</h2>
    <li>{{ post.content }}</li>
    <p>{{ post.created_at }}</p>

{% endblock content %}

templates/forum/post-update.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2>Post update</h2>
                    <form method="post" action="{% url 'forum:update-post' post.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/forum/post_confirm_delete.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2>Are you sure you want to delete this post?</h2>
                    <form method="post" action="{% url 'forum:delete-post' post.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/forum/posts.html
{% extends 'index.html' %}
{% block content %}
    <div class="container">
        <h2 class="mb-4">Discussion</h2>
        <div class="row">
            <div class="col-md-8">
                <form method="post" action="{% url 'forum:posts' topic.id %}" class="mb-4">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">Post</button>
                </form>
                <ul class="list-unstyled list-group">
                    {% for post in page_obj %}
                        <li class="list-group-item">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <h5 class="mb-0">{{ post.title }}</h5>
                                    <p class="mb-0">{{ post.content }}</p>
                                    <small class="text-muted">by {{ post.author }}</small><br>
                                    <small class="text-muted">{{ post.created_at }}</small>
                                </div>
                                {% if request.user.is_authenticated and request.user.id == post.author.id %}
                                    <div>
                                        <nav class="navbar navbar-expand-lg">
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                                                        <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/>
                                                    </svg>
                                                </a>
                                                <ul class="list-unstyled dropdown-menu me-auto mb-2 mb-lg-0">
                                                    <li>
                                                        <a href="{% url 'forum:update-post' post.id %}" class="btn btn-sm btn-outline-secondary mr-2">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                                                                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001"/>
                                                            </svg> Edit
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="{% url 'forum:delete-post' post.id %}" class="btn btn-sm btn-outline-danger">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                                                <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                                                            </svg> Delete
                                                        </a>
                                                    </li>
                                                </ul>
                                            </li>
                                        </nav>
                                    </div>
                                {% endif %}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-4">
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                {% for page_num in page_obj.paginator.page_range %}
                <a href="?page={{ page_num }}" class="display: inline-block link-offset-2 link-underline link-underline-opacity-0">{{ page_num }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/forum/topic-creation.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2>Topic creation</h2>
                    <form method="post" action="{% url 'forum:create-topic' category.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary" type="submit">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>    
{% endblock content %}

templates/forum/topic-update.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2>Topic update</h2>
                    <form method="post" action="{% url 'forum:update-topic' topic.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/forum/topic_confirm_delete.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2>Are you sure you want to delete {{ topic.title }} topic?</h2>
                    <form method="post" action="{% url 'forum:delete-topic' topic.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/forum/topics.html
{% extends 'index.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% if topics %}
                    <h2 class="mb-4">Topics</h2>
                    <ul class="list-group">
                        {% for topic in page_obj %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <a href="{% url 'forum:posts' topic.id %}" class="text-dark link-offset-2 link-underline link-underline-opacity-0">{{ topic.title }}</a>
                                {% if request.user.is_authenticated and request.user.id == topic.creator.id %}
                                    <div class="btn-group">
                                        <a href="{% url 'forum:update-topic' topic.id %}" class="btn btn-sm btn-outline-secondary">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                                                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001"/>
                                            </svg>
                                        </a>
                                        <a href="{% url 'forum:delete-topic' topic.id %}" class="btn btn-sm btn-outline-danger">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                                <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                                            </svg>
                                        </a>
                                    </div>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            No topics yet...
                        </li>
                    </ul>
                {% endif %}
            </div>
            <div class="col-md-4">
                {% if request.user.is_authenticated %}
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">Actions</h5>
                            <a href="{% url 'forum:create-topic' category.id %}" class="btn btn-primary btn-block">Create Topic</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                {% for page_num in page_obj.paginator.page_range %}
                <a href="?page={{ page_num }}" class="display: inline-block link-offset-2 link-underline link-underline-opacity-0">{{ page_num }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}